# Specify the version of Docker Compose
version: '3.8'

# Define services
services:
  
  # Define Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:3.8.1
    networks:
      - app-tier
    ports:
      - "2181:2181"



  # Define Apache Kafka
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper



  # Define the ingester service
  ingester:
    # Build the Docker image from the especified directory
    build: ./ingester
    depends_on:
      - kafka



  # Define the PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"



  # Define Kafka Connect
  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "quickstart"
      CONNECT_CONFIG_STORAGE_TOPIC: "docker-connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "docker-connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "docker-connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_PLUGIN_PATH: "/usr/share/java"
    depends_on:
      - kafka
      - postgres
    volumes:
      - ./connect-plugins:/usr/share/java



  # Define Kafka connect setup
  kafka-connect-setup:
    image: curlimages/curl:latest
    depends_on:
      - kafka-connect
    entrypoint: >
      sh -c "
      while [ $(curl -s -o /dev/null -w %{http_code} http://kafka-connect:8083/) -ne 200 ]; do
        echo 'Waiting for Kafka Connect to start...';
        sleep 5;
      done;
      curl -X POST -H 'Content-Type: application/json' --data @/connectors/jdbc-sink-config.json http://kafka-connect:8083/connectors;
      "
    volumes:
      - ./connectors:/connectors