# Specify the version of Docker Compose
version: '3'

# Define services
services:
  
  # Define the PostgreSQL service
  postgresdb:
    image: postgres
    restart: always
    ports:
    - "5433:5432"
    environment:
      # The only obligatory enviroment variable of the postgres image
      POSTGRES_PASSWORD: rootroot
    volumes:
      - postgres_data:/var/lib/postgresql/data



    # Define Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:3.8.1
    networks:
      - app-tier
    ports:
      - "2181:2181"

  # Define Apache Kafka
  kafka:
    image: bitnami/kafka:latest
    networks:
      - app-tier
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"

  # Define Kafka Connect
  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    networks:
      - app-tier
    depends_on:
      - kafka
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_REST_PORT=8083
      - CONNECT_GROUP_ID="connect-cluster"
      - CONNECT_CONFIG_STORAGE_TOPIC="connect-configs"
      - CONNECT_OFFSET_FLUSH_INTERVAL_MS=10000
      - CONNECT_OFFSET_STORAGE_TOPIC="connect-offsets"
      - CONNECT_STATUS_STORAGE_TOPIC="connect-status"
    ports:
      - "8083:8083"



  # Define the ingester service
  ingester:
    # Build the Docker image from the current directory
    build: .

    # Map port 5000 on the host to port 5000 on the container
    ports:
      - "7000:7000"

    volumes:

    environment:
